[package]
name = "test-com-impl"
version = "0.1.0"
authors = ["Connie Hilarides <conni_h@outlook.com>"]
edition = "2018"

[dependencies]
com-impl = { path = "../com-impl" }
wio = "0.2.0"

[dependencies.winapi]
version = "0.3.6"
features = ["dwrite"]

